// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
		seed: "node prisma/seed.js",
	},
	// 'datasource'를 'datasources' (복수, plural)로 변경하고,
	// 환경 변수는 process.env를 사용하도록 수정합니다.
	datasource: {
		url: process.env.DATABASE_URL ?? "",
	},
});
